# Generated by Django 5.0.11 on 2025-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdemand',
            name='uploaded_data',
            field=models.JSONField(null=True),
        ),
    ]
