# Generated by Django 5.0.11 on 2025-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='griddesign',
            name='connection_cable_capex',
            field=models.FloatField(db_column='connection_cable__capex', default=4),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='connection_cable_lifetime',
            field=models.PositiveSmallIntegerField(db_column='connection_cable__lifetime', default=25),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='connection_cable_max_length',
            field=models.FloatField(db_column='connection_cable__max_length', default=20),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='distribution_cable_capex',
            field=models.FloatField(db_column='distribution_cable__capex', default=10),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='distribution_cable_lifetime',
            field=models.PositiveSmallIntegerField(db_column='distribution_cable__lifetime', default=25),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='distribution_cable_max_length',
            field=models.FloatField(db_column='distribution_cable__max_length', default=50),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='include_shs',
            field=models.BooleanField(db_column='shs__include', default=True),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='mg_connection_cost',
            field=models.FloatField(db_column='mg__connection_cost', default=140),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='pole_capex',
            field=models.FloatField(db_column='pole__capex', default=800),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='pole_lifetime',
            field=models.PositiveSmallIntegerField(db_column='pole__lifetime', default=25),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='pole_max_n_connections',
            field=models.PositiveSmallIntegerField(db_column='pole__max_n_connections', default=5),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='shs_max_grid_cost',
            field=models.FloatField(blank=True, db_column='shs__max_grid_cost', default=0.6, null=True),
        ),
    ]
