# Generated by Django 5.0.11 on 2025-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_customdemand_uploaded_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energysystemdesign',
            name='battery_settings_design',
            field=models.BooleanField(db_column='battery__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='battery_settings_is_selected',
            field=models.BooleanField(db_column='battery__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='diesel_genset_settings_design',
            field=models.BooleanField(db_column='diesel_genset__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='diesel_genset_settings_is_selected',
            field=models.BooleanField(db_column='diesel_genset__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='inverter_settings_design',
            field=models.BooleanField(db_column='inverter__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='inverter_settings_is_selected',
            field=models.BooleanField(db_column='inverter__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='pv_settings_design',
            field=models.BooleanField(db_column='pv__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='pv_settings_is_selected',
            field=models.BooleanField(db_column='pv__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='rectifier_settings_design',
            field=models.BooleanField(db_column='rectifier__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='rectifier_settings_is_selected',
            field=models.BooleanField(db_column='rectifier__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='shortage_settings_is_selected',
            field=models.FloatField(db_column='shortage__settings__is_selected', default=False),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='connection_cable_capex',
            field=models.FloatField(db_column='connection_cable__capex', default=4),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='connection_cable_lifetime',
            field=models.PositiveSmallIntegerField(db_column='connection_cable__lifetime', default=25),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='connection_cable_max_length',
            field=models.FloatField(db_column='connection_cable__max_length', default=20),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='distribution_cable_capex',
            field=models.FloatField(db_column='distribution_cable__capex', default=10),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='distribution_cable_lifetime',
            field=models.PositiveSmallIntegerField(db_column='distribution_cable__lifetime', default=25),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='distribution_cable_max_length',
            field=models.FloatField(db_column='distribution_cable__max_length', default=50),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='include_shs',
            field=models.BooleanField(db_column='shs__include', default=True),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='mg_connection_cost',
            field=models.FloatField(db_column='mg__connection_cost', default=140),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='pole_capex',
            field=models.FloatField(db_column='pole__capex', default=800),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='pole_lifetime',
            field=models.PositiveSmallIntegerField(db_column='pole__lifetime', default=25),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='pole_max_n_connections',
            field=models.PositiveSmallIntegerField(db_column='pole__max_n_connections', default=5),
        ),
        migrations.AlterField(
            model_name='griddesign',
            name='shs_max_grid_cost',
            field=models.FloatField(blank=True, db_column='shs__max_grid_cost', default=0.6, null=True),
        ),
    ]
