# Generated by Django 5.0.11 on 2025-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_alter_griddesign_connection_cable_capex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energysystemdesign',
            name='battery_settings_design',
            field=models.BooleanField(db_column='battery__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='battery_settings_is_selected',
            field=models.BooleanField(db_column='battery__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='diesel_genset_settings_design',
            field=models.BooleanField(db_column='diesel_genset__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='diesel_genset_settings_is_selected',
            field=models.BooleanField(db_column='diesel_genset__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='inverter_settings_design',
            field=models.BooleanField(db_column='inverter__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='inverter_settings_is_selected',
            field=models.BooleanField(db_column='inverter__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='pv_settings_design',
            field=models.BooleanField(db_column='pv__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='pv_settings_is_selected',
            field=models.BooleanField(db_column='pv__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='rectifier_settings_design',
            field=models.BooleanField(db_column='rectifier__settings__design', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='rectifier_settings_is_selected',
            field=models.BooleanField(db_column='rectifier__settings__is_selected', default=True),
        ),
        migrations.AlterField(
            model_name='energysystemdesign',
            name='shortage_settings_is_selected',
            field=models.FloatField(db_column='shortage__settings__is_selected', default=False),
        ),
    ]
