# Generated by Django 5.0.11 on 2025-03-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_alter_energysystemdesign_battery_settings_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energysystemdesign',
            name='shortage_settings_is_selected',
        ),
    ]
