# Generated by Django 5.0.11 on 2025-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_remove_energysystemdesign_shortage_settings_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='energysystemdesign',
            name='shortage_settings_is_selected',
            field=models.BooleanField(db_column='shortage__settings__is_selected', default=False),
        ),
    ]
