# Generated by Django 5.1.8 on 2025-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_alter_customdemand_high_alter_customdemand_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_parameters_capex',
            field=models.FloatField(blank=True, db_column='electrolyzer__parameters__capex', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_parameters_efficiency',
            field=models.FloatField(blank=True, db_column='electrolyzer__parameters__efficiency', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_parameters_lifetime',
            field=models.PositiveIntegerField(blank=True, db_column='electrolyzer__parameters__lifetime', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_parameters_nominal_capacity',
            field=models.FloatField(blank=True, db_column='electrolyzer__parameters__nominal_capacity', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_parameters_opex',
            field=models.FloatField(blank=True, db_column='electrolyzer__parameters__opex', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_settings_design',
            field=models.BooleanField(db_column='electrolyzer__settings__design', default=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_settings_is_selected',
            field=models.BooleanField(db_column='electrolyzer__settings__is_selected', default=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_parameters_capex',
            field=models.FloatField(blank=True, db_column='fuel_cell__parameters__capex', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_parameters_efficiency',
            field=models.FloatField(blank=True, db_column='fuel_cell__parameters__efficiency', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_parameters_lifetime',
            field=models.PositiveIntegerField(blank=True, db_column='fuel_cell__parameters__lifetime', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_parameters_nominal_capacity',
            field=models.FloatField(blank=True, db_column='fuel_cell__parameters__nominal_capacity', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_parameters_opex',
            field=models.FloatField(blank=True, db_column='fuel_cell__parameters__opex', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_settings_design',
            field=models.BooleanField(db_column='fuel_cell__settings__design', default=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_settings_is_selected',
            field=models.BooleanField(db_column='fuel_cell__settings__is_selected', default=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_parameters_capex',
            field=models.FloatField(blank=True, db_column='h2_storage__parameters__capex', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_parameters_efficiency',
            field=models.FloatField(blank=True, db_column='h2_storage__parameters__efficiency', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_parameters_lifetime',
            field=models.PositiveIntegerField(blank=True, db_column='h2_storage__parameters__lifetime', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_parameters_nominal_capacity',
            field=models.FloatField(blank=True, db_column='h2_storage__parameters__nominal_capacity', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_parameters_opex',
            field=models.FloatField(blank=True, db_column='h2_storage__parameters__opex', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_parameters_soc_max',
            field=models.FloatField(blank=True, db_column='h2_storage__parameters__soc_max', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_parameters_soc_min',
            field=models.FloatField(blank=True, db_column='h2_storage__parameters__soc_min', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_settings_design',
            field=models.BooleanField(db_column='h2_storage__settings__design', default=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='h2_storage_settings_is_selected',
            field=models.BooleanField(db_column='h2_storage__settings__is_selected', default=True),
        ),
    ]
