# Generated by Django 5.2.5 on 2026-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_energysystemdesign_electrolyzer_parameters_capex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_parameters_fuel_lhv',
            field=models.FloatField(blank=True, db_column='fuel_cell__parameters__fuel_lhv', null=True),
        ),
    ]
