# Generated by Django 5.2.5 on 2026-02-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_energysystemdesign_fuel_cell_parameters_fuel_lhv'),
    ]

    operations = [
        migrations.AddField(
            model_name='energysystemdesign',
            name='electrolyzer_parameters_variable_cost',
            field=models.FloatField(blank=True, db_column='electrolyzer__parameters__variable_cost', null=True),
        ),
        migrations.AddField(
            model_name='energysystemdesign',
            name='fuel_cell_parameters_variable_cost',
            field=models.FloatField(blank=True, db_column='fuel_cell__parameters__variable_cost', null=True),
        ),
    ]
