# Generated by Django 5.2.5 on 2026-03-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0009_energysystemdesign_electrolyzer_parameters_variable_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdemand',
            name='very_high',
        ),
        migrations.RemoveField(
            model_name='customdemand',
            name='very_low',
        ),
    ]
