# Generated by Django 5.1.8 on 2026-03-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0010_remove_customdemand_very_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdemand',
            name='annual_demand_increase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
