# Generated by Django 5.0.11 on 2025-04-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
