# Generated by Django 5.1.8 on 2025-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0002_alter_simulation_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='task_id',
            new_name='task_supply',
        ),
        migrations.AddField(
            model_name='simulation',
            name='task_grid',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
