# Generated by Django 5.0.11 on 2025-03-12 11:56

import django.core.validators
import django.db.models.deletion
import offgridplanner.projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notification', models.BooleanField(default=False)),
                ('do_demand_estimation', models.BooleanField(default=True)),
                ('do_grid_optimization', models.BooleanField(default=True)),
                ('do_es_design_optimization', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=51, null=True)),
                ('description', models.CharField(blank=True, max_length=201, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('lifetime', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)])),
                ('start_date', models.DateTimeField(default=offgridplanner.projects.models.default_start_date)),
                ('temporal_resolution', models.PositiveSmallIntegerField(default=1)),
                ('n_days', models.PositiveSmallIntegerField(default=365)),
                ('options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.options')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
