# Generated by Django 5.0.11 on 2025-03-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherdata",
            unique_together=set(),
        ),
    ]
