# Generated by Django 5.0.11 on 2025-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_weatherdata_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energysystemdesign",
            name="battery_settings_design",
            field=models.BooleanField(
                blank=True, db_column="battery__settings__design", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="battery_settings_is_selected",
            field=models.BooleanField(
                blank=True, db_column="battery__settings__is_selected", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="diesel_genset_settings_design",
            field=models.BooleanField(
                blank=True, db_column="diesel_genset__settings__design", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="diesel_genset_settings_is_selected",
            field=models.BooleanField(
                blank=True, db_column="diesel_genset__settings__is_selected", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="inverter_settings_design",
            field=models.BooleanField(
                blank=True, db_column="inverter__settings__design", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="inverter_settings_is_selected",
            field=models.BooleanField(
                blank=True, db_column="inverter__settings__is_selected", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="pv_settings_design",
            field=models.BooleanField(
                blank=True, db_column="pv__settings__design", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="pv_settings_is_selected",
            field=models.BooleanField(
                blank=True, db_column="pv__settings__is_selected", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="rectifier_settings_design",
            field=models.BooleanField(
                blank=True, db_column="rectifier__settings__design", null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysystemdesign",
            name="rectifier_settings_is_selected",
            field=models.BooleanField(
                blank=True, db_column="rectifier__settings__is_selected", null=True
            ),
        ),
    ]
