# Generated by Django 5.1.8 on 2026-04-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('THB', 'Thai Baht')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='exchange_rate',
            field=models.FloatField(default=1.0, help_text='Exchange rate relative to base currency'),
        ),
    ]
