# Generated by Django 5.1.8 on 2026-04-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_currency_project_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('THB', 'Thai Baht')], max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='exchange_rate',
            field=models.FloatField(),
        ),
    ]
