# Generated by Django 5.2.5 on 2026-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_currency_alter_project_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('NGN', 'Nigerian Naira')], max_length=3),
        ),
    ]
