#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo MANAGETRANSLATIONS
python manage.py compilemessages --locale=th
python manage.py compilejsi18n -d djangojs

echo COLLECTSTATIC
python manage.py collectstatic --noinput

compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  echo COMPRESSING
  python /app/manage.py compress
fi

echo RUNNING
exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn_worker.UvicornWorker
